name: Update GitHub Metrics

on:
  schedule:
    # Запуск каждый день в полночь UTC
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: RoXyGeNOFF
          filename: github-metrics.svg
          base: header, activity, community, repositories, metadata
          config_octicon_animate: true
          config_display: large
          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: X
          plugin_contributors: yes
          plugin_contributors_limit: 24
          plugin_contributors_size: 24
          plugin_contributors_contributions: yes
          plugin_discussions: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: *
          plugin_languages_recent_load: 300
          plugin_languages_recent_days: 14
          plugin_languages_sections: most-used
          plugin_licenses: yes
          plugin_licenses_legal: yes
          plugin_licenses_license: free
          plugin_lines: yes
          plugin_notable: yes
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 24
          plugin_people_types: followers, following
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_url: https://denisnekrasov.dev
          plugin_reactions: yes
          plugin_reactions_limit: 24
          plugin_skyline: yes
          plugin_skyline_year: current-year
          plugin_stargazers: yes
          plugin_stargazers_limit: 24
          plugin_stargazers_random: yes
          plugin_stargazers_sponsors: yes
          plugin_stargazers_sponsors_limit: 24
          plugin_stargazers_sponsors_random: yes
          plugin_stars: yes
          plugin_stars_limit: 24
          plugin_stars_random: yes
          plugin_topics: yes
          plugin_topics_limit: 9
          plugin_topics_mode: starred
          plugin_traffic: yes
          plugin_wakatime: no

      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add github-metrics.svg
          git diff --staged --quiet || git commit -m "Update GitHub metrics [skip ci]"
          git push

